language: python
python:
  - "3.5"
env:
  matrix:
    - TOXENV=py35
    - TOXENV=py36
    - TOXENV=py37
    - TOXENV=py38
    - TOXENV=pypy3
install:
  - travis_retry pip install tox
script:
  - make test
